name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0' # Latest LTS
    - name: Configure Git
      run: |
        git config --global user.email "m0smith@yahoo.com"
        git config --global user.name "Matthew O. Smith"

    - name: Install Dependencies
      run: yarn install

    - name: Deploy
      run: yarn deploy
