name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        persist-credentials: false 

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0' # Latest LTS

    - name: Configure Git
      run: |
        git config --global user.email "m0smith@yahoo.com"
        git config --global user.name "Matthew O. Smith"

    - name: Install Dependencies
      run: yarn install

    - name: Build 
      run: yarn build
    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: build # The folder the action should deploy.

    # - name: Deploy
    #   run: yarn deploy
    #   env:
    #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
